### ISSUE TITLE
NO_DUPLICATES causes deadlock as multiple tasks try to insert data into same global temp table

### ISSUE THREAD

**Issue by ankitbko** [microsoft/sql-spark-connector#49] opened 2020-09-05 07:56 UTC
Because the temp table remains unique to a worker for a table, multiple tasks executing on the same worker will result in deadlock,

![image](https://user-images.githubusercontent.com/3169316/92300793-6a338a80-ef7b-11ea-96c7-b5222d837b06.png)

**Comment by pramodnagare** [comment] 2020-10-08 20:41
Hi  ankitbko 
Try adding below option, it will solve your table lock issue.

**option("tableLock", True)**

**Comment by ankitbko** [comment] 2020-10-09 04:05
@pramodnagare `tablelock` option is meant to be used with heap tables only. `tablelock` option is set to true automatically for staging tables.  https://github.com/microsoft/sql-spark-connector/blob/526f08dec3c6f12e375527d8c5c7531db4ea2864/src/main/scala/com/microsoft/sqlserver/jdbc/spark/connectors/ReliableSingleInstanceStrategy.scala#L85

cc: @shivsood

**Comment by bunkersdev** [comment] 2020-10-12 17:11
Hello, I am encountering the same issue. I need to use the following options 
`        .option("schemaCheckEnabled", False) \
            .option("reliabilityLevel","NO_DUPLICATES") \`

**Comment by bunkersdev** [comment] 2020-11-02 15:10
Any update on this ?

**Comment by shivsood** [comment] 2021-06-07 21:31
@ankitbko does this happen only on databricks? Can u send repro step and your scripts for us to repro this. @luxu1-ms as FYI

**Comment by gerardwolf** [comment] 2021-08-23 03:19
I also encounter this issue when running multiple instances of the same notebook on the same cluster (DBR 7.3 LTS) using Azure Databricks. My notebook attempts to load data from delta lake table source and to overwrite the data in an Azure SQL Database table using the following options:
`try:
  dfSource.write \
    .format("com.microsoft.sqlserver.jdbc.spark") \
    .mode("overwrite") \
    .option("url", url) \
    .option("dbtable", sinkTable) \
    .option("user", userName) \
    .option("password", password) \
    .option("truncate", "true") \
    .option("tablock", "true") \
    .option("schemaCheckEnabled", "false") \
    .option("batchsize", batchsize) \
    .option("reliabilityLevel", "NO_DUPLICATES") \
    .save()
except ValueError as error :
    print("Connector write failed", error)`

The intent is to preserve the table definition (and indexes) in the sink database. I realise the tablock is only required for heaps, but this is a generic notebook that loads to both indexed and heap tables.
Importantly, I don't get an error when I run the notebook in isolation, so it appears that there is some shared global temp table that is causing deadlocks in parallel execution scenario.

**Comment by luxu1-ms** [comment] 2021-08-23 21:46
I think this issue is related with #132

**Comment by gerardwolf** [comment] 2021-08-23 21:58
Certainly looks like it is caused by the name of the temp staging table not being granular enough. Adding the sink table name to the temp table should resolve this yes.

**Comment by luxu1-ms** [comment] 2021-09-27 18:47
@ankitbko Could you please provide repro scripts? I am not able to repro this issue.

**Comment by luxu1-ms** [comment] 2021-10-04 18:37
Close this issue since no more info provided and cannot repro it. Please reopen if more info provided.

**Closed by luxu1-ms** 2021-10-04 18:37 UTC
Labels: enhancement, more information needed
