### ISSUE TITLE
ReliableSingleInstanceStrategy does not run union table on exectuor

### ISSUE THREAD

**Issue by ankitbko** [microsoft/sql-spark-connector#48] opened 2020-09-05 07:29 UTC
`ReliableSingleInstanceStrategy` does not run phase 2 (union) on executors/workers. It runs this phase on driver. This means it does is not a spark job and does not show up in Spark UI. Is it by design?

Currently the phase 1 shows up as spark job with multiple tasks (1 for each partition) however when it completes the command itself does not complete as phase 2 is still running in driver and as result no update is shown to the user. Ask is to submit union task to executor so it shows up properly in Spark UI.

**Comment by shivsood** [comment] 2021-06-07 21:28
Closing as by design.  Driver needs to wait for all executors to finish staging table writes, before union to final table. 

@luxu1-ms

**Closed by shivsood** 2021-06-07 21:28 UTC
