### ISSUE TITLE
can't write synapse table with date/timestamp type

### ISSUE THREAD

**Issue by liuhaoran** [microsoft/sql-spark-connector#35] opened 2020-08-05 02:43 UTC
i have create table  in synapse like this:
``` SQL
create table tb_trans_synapse
(
col1     int,
col2 int,
col3 int,
col4 date
);
```
while my databricks notebook code is this:
```python
 df.write \
           .format("com.microsoft.sqlserver.jdbc.spark") \
           .mode("overwrite") \
           .option("truncate","true") \
           .option("url", url) \
           .option("dbtable", table_name) \
           .option("user", username) \
           .option("password", password) \
           .option("BatchSize","100000") \
           .option("autotranslate","true") \
           .option("mssqlIsolationLevel", "READ_UNCOMMITTED") \
           .save()
```
dateframe's schema is :
```JSON
root
 |-- col1: integer (nullable = true)
 |-- col2: integer (nullable = true)
 |-- col3: integer (nullable = true)
 |-- col4: date (nullable = true)
```

but some exception happened:
```
SqlNativeBufferBufferBulkCopy.WriteTdsDataToServer, error in OdbcDone: SqlState: 42000, NativeError: 4816, 'Error calling: bcp_done(this->GetHdbc()) | SQL Error Info: SrvrMsgState: 1, SrvrSeverity: 16,  Error <1>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column type from bcp client for colid 4. | Error calling: pConn->Done() | state: FFFF, number: 4141, active connections: 36', Connection String: Driver={pdwodbc17e};app=TypeD00-DmsNativeWriter:DB55\mpdwsvc (19024)-ODBC;autotranslate=no;trusted_connection=yes;server=\\.\pipe\DB.55-b2bbd12c7078-0\sql\query;database=Distribution_2
```

is that an issue writing data to synapse table with date/timestmap type ?

**Comment by shivsood** [comment] 2020-08-10 23:53
can u please enable logging in your spark application and send the log
From exception this looks like a case of mismatched column types. Does this work when you set .option("truncate","false")?

**Comment by shivsood** [comment] 2021-06-07 21:20
Closing as dupe of #39 

@luxu1-ms

**Closed by shivsood** 2021-06-07 21:20 UTC
Labels: more information needed

**Comment by chopraarjun** [comment] 2021-07-01 19:31
I am facing the same issue... Date and DateTime2 is not working with synapse even with append mode
